use colored::Colorize;
use std::fs;
use std::path::Path;
use std::process;

use crate::config::{config_to_toml, detect_source_dirs};
use crate::types::SpecSyncConfig;

/// Version stamp written to `.specsync/version` for fresh v4 projects.
const V4_VERSION: &str = "4.0.0";

/// Subdirectories created inside `.specsync/` for a fresh v4 project.
const V4_DIRS: &[&str] = &[
    ".specsync/lifecycle",
    ".specsync/changes",
    ".specsync/archive",
];

pub fn cmd_init(root: &Path) {
    // Refuse to clobber any existing config — v4 or legacy.
    let v4_toml = root.join(".specsync/config.toml");
    let v4_json = root.join(".specsync/config.json");
    let legacy_json = root.join("specsync.json");
    let legacy_toml = root.join(".specsync.toml");
    if v4_toml.exists() {
        println!(".specsync/config.toml already exists");
        return;
    }
    if v4_json.exists() {
        println!(".specsync/config.json already exists");
        return;
    }
    if legacy_json.exists() {
        println!("specsync.json already exists (legacy 3.x layout — run `specsync migrate`)");
        return;
    }
    if legacy_toml.exists() {
        println!(".specsync.toml already exists (legacy 3.x layout — run `specsync migrate`)");
        return;
    }

    let detected_dirs = detect_source_dirs(root);
    let dirs_display = detected_dirs.join(", ");

    if let Err(e) = write_v4_layout(root, &detected_dirs) {
        eprintln!("{} {e}", "error:".red().bold());
        process::exit(1);
    }

    println!("{} Created .specsync/config.toml (v4 layout)", "✓".green());
    println!("  Detected source directories: {dirs_display}");

    // Ensure .specsync/hashes.json is gitignored (hash cache is local-only)
    match ensure_hashes_gitignored(root) {
        Ok(true) => println!("{} Added .specsync/hashes.json to .gitignore", "✓".green()),
        Ok(false) => {}
        Err(e) => eprintln!("{} {e}", "warning:".yellow().bold()),
    }
}

/// Create the v4 `.specsync/` directory structure: directories, `config.toml`,
/// `version` stamp, and `.specsync/.gitignore`. Mirrors what `specsync migrate`
/// produces so a fresh `init` never triggers the legacy-layout migration nag.
fn write_v4_layout(root: &Path, source_dirs: &[String]) -> Result<(), String> {
    for dir in V4_DIRS {
        fs::create_dir_all(root.join(dir)).map_err(|e| format!("Failed to create {dir}: {e}"))?;
    }

    let config = SpecSyncConfig {
        source_dirs: source_dirs.to_vec(),
        ..Default::default()
    };
    let config_path = root.join(".specsync/config.toml");
    fs::write(&config_path, config_to_toml(&config))
        .map_err(|e| format!("Failed to write .specsync/config.toml: {e}"))?;

    let version_path = root.join(".specsync/version");
    fs::write(&version_path, format!("{V4_VERSION}\n"))
        .map_err(|e| format!("Failed to write .specsync/version: {e}"))?;

    let gitignore_path = root.join(".specsync/.gitignore");
    if !gitignore_path.exists() {
        let content = [
            "# spec-sync v4 — generated by `specsync init`",
            "# Committed: config.toml, registry.toml, lifecycle/, changes/, archive/",
            "# Ignored: backups, local config, hash cache (regenerated on each run)",
            "",
            "backup-3x/",
            "config.local.toml",
            "hashes.json",
            "",
        ]
        .join("\n");
        fs::write(&gitignore_path, content)
            .map_err(|e| format!("Failed to write .specsync/.gitignore: {e}"))?;
    }

    Ok(())
}

/// Append `.specsync/hashes.json` to the root `.gitignore` if not already present.
/// Returns `Ok(true)` if added, `Ok(false)` if already present, `Err` on write failure.
pub fn ensure_hashes_gitignored(root: &Path) -> Result<bool, String> {
    let gitignore_path = root.join(".gitignore");
    let entry = ".specsync/hashes.json";

    let existing = fs::read_to_string(&gitignore_path).unwrap_or_default();
    if existing.lines().any(|line| line.trim() == entry) {
        return Ok(false);
    }

    let mut content = existing;
    if !content.is_empty() && !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(&format!(
        "\n# spec-sync hash cache (regenerated locally)\n{entry}\n"
    ));

    fs::write(&gitignore_path, content).map_err(|e| format!("Failed to update .gitignore: {e}"))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn adds_entry_to_missing_gitignore() {
        let tmp = TempDir::new().unwrap();
        let changed = ensure_hashes_gitignored(tmp.path()).unwrap();
        assert!(changed, "should report it wrote the entry");

        let content = fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
        assert!(content.contains(".specsync/hashes.json"));
    }

    #[test]
    fn is_idempotent_when_entry_already_present() {
        let tmp = TempDir::new().unwrap();
        fs::write(
            tmp.path().join(".gitignore"),
            "target/\n.specsync/hashes.json\n",
        )
        .unwrap();

        let changed = ensure_hashes_gitignored(tmp.path()).unwrap();
        assert!(!changed, "entry already present — nothing to add");

        // Existing content is untouched (no duplicate entry appended).
        let content = fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
        assert_eq!(content.matches(".specsync/hashes.json").count(), 1);
    }

    #[test]
    fn errors_when_gitignore_path_is_unwritable() {
        let tmp = TempDir::new().unwrap();
        // Make `.gitignore` a directory so the write fails — exercises the
        // error path that maps the io::Error into a String.
        fs::create_dir(tmp.path().join(".gitignore")).unwrap();

        let result = ensure_hashes_gitignored(tmp.path());
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Failed to update .gitignore"));
    }

    #[test]
    fn write_v4_layout_creates_full_structure() {
        let tmp = TempDir::new().unwrap();
        write_v4_layout(tmp.path(), &["src".to_string()]).unwrap();

        assert!(tmp.path().join(".specsync/config.toml").exists());
        assert!(tmp.path().join(".specsync/version").exists());
        assert!(tmp.path().join(".specsync/.gitignore").exists());
        assert!(tmp.path().join(".specsync/lifecycle").is_dir());
        assert!(tmp.path().join(".specsync/changes").is_dir());
        assert!(tmp.path().join(".specsync/archive").is_dir());

        let version = fs::read_to_string(tmp.path().join(".specsync/version")).unwrap();
        assert_eq!(version.trim(), V4_VERSION);

        let config = fs::read_to_string(tmp.path().join(".specsync/config.toml")).unwrap();
        assert!(config.contains("specs_dir = \"specs\""));
        assert!(config.contains("source_dirs = [\"src\"]"));
        assert!(config.contains("required_sections"));
    }

    #[test]
    fn fresh_init_is_not_legacy_layout() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir_all(tmp.path().join("src")).unwrap();
        cmd_init(tmp.path());
        assert!(
            !crate::config::is_legacy_layout(tmp.path()),
            "fresh init must produce a v4 layout that does not trigger the migration nag"
        );
    }
}
